### ISSUE TITLE
Better example code in README

### ISSUE THREAD

**Issue by lfarah** [exyte/FloatingButton#1]
Hey, FloatingButton looks awesome! As I understand you have an example project, it would be good to have a couple of lines in the README. You can follow [cariocamenu](https://github.com/arn00s/cariocamenu#-usage) as an example

**Comment by shipinev** [comment]
Hey @lfarah. Thanks for reaching us out :)
I want to clarify your suggestion. Do you wish us to add more code from the example project to the usage section?

**Comment by lfarah** [comment]
Yeah, that would be good!

**Comment by f3dm76** [comment]
Hello @lfarah ,
I know it's been a while, sorry for the delay. It's a good suggestion to have a couple of complete examples in readme, so I added them. Please let me know if you want to see anything else there, have a great day!

**Comment by lfarah** [comment]
Hey @f3dm76, great update! The README looks awesome now 🎉
