### ISSUE TITLE
Not working on iOS 13

### ISSUE THREAD

**Issue by HonQii** [exyte/FloatingButton#10]
FloatingButton on iOS 13 can not show submenu buttons. May be affected by Spacer!

The code in the example app also doesn’t work

**Comment by f3dm76** [comment]
Hey @HonQii, extremely sorry for super late response, I think you are using iOS 15 by now, but please do let me know if you have any more trouble with the library. Thank you for reaching out, have a great day!

**Comment by f3dm76** [comment]
Closing this for now, do not hesitate to reach out again, if the problem persists

**Comment by ValS01** [comment]
The problem is still active
When I try to use the library in iOS 13 it doesn't work, a shame I can't use it.
