### ISSUE TITLE
precondition failure: invalid input index: 2    run error

### ISSUE THREAD

**Issue by zhanggenlove** [exyte/FloatingButton#2]
var body: some View {
        GeometryReader { geometry in
            Rectangle()
                .fill(Color.clear)
                .preference(key: SubmenuButtonPreferenceKey.self,
                            value: [geometry.frame(in: .named("ExampleButtonSpace")).size])
        }
    }

**Comment by f3dm76** [comment]
Hello @zhanggenlove , just wanted to let you know that we are working on this problem. Right now it looks like SwiftUI 5.2 bug (it works on previous revisions), and we filed Apple bug report, but the response is yet to come. We will keep you informed, sorry it takes so long.

**Comment by f3dm76** [comment]
Hello again, while we wait I updated the example so that it will work. However if you try using FloatingButton inside NavigationView it might happen again. Here is the bug report to Apple concerning the issue.
https://feedbackassistant.apple.com/feedback/7689920

**Comment by f3dm76** [comment]
Hey @zhanggenlove , Apple fixed the issue, the error in no more in Xcode Version 12.0 beta, you are welcome to check it out, have a great day!
