### ISSUE TITLE
Example project cannot be run successfully 

### ISSUE THREAD

**Issue by patr1ckzhu** [exyte/FloatingButton#4]
**After I clone and install pods, the project cannot be successfully run.**
<img width="1280" alt="Screen 2020-05-13 at 12 19 48 AM" src="https://user-images.githubusercontent.com/46059506/81719555-ca279200-94af-11ea-90e4-e13b0f952f39.png">

My iPhone system is iOS 13.4
Xcode also running under the latest version.

**Comment by f3dm76** [comment]
Hello, I updated the example so that it will work. However if you try using FloatingButton inside NavigationView it might happen again. Here is the bug report to Apple concerning the issue.
https://feedbackassistant.apple.com/feedback/7689920

**Comment by patr1ckzhu** [comment]
Okay, now the example project can be successfully run, but I need to embed it in NavigationView.
Hope that Apple can fix the bug, Thanks!

**Comment by f3dm76** [comment]
Hey @OOXXXX, Apple fixed the issue, the error in no more in Xcode Version 12.0 beta, you are welcome to check it out, have a great day!

**Comment by patr1ckzhu** [comment]
Thanks, that's awesome!
