### ISSUE TITLE
How to close menu?

### ISSUE THREAD

**Issue by philipborbon** [exyte/FloatingButton#6]
How to close menu after button is clicked?

**Comment by f3dm76** [comment]
Hey @philipborbon , in the new 0.0.2 version I've added the ability to pass a binding into FloatingButton's constructor, so you can control the closing of the menu from your end. I modified the first menu from example project to work like what you've described, you are most welcome to check it out. Have a wonderful day!

**Comment by philipborbon** [comment]
Thanks for the update @f3dm76.

Kudos for more awesome SwiftUI components.
