### ISSUE TITLE
Thread 1: Fatal error: Index out of range

### ISSUE THREAD

**Issue by benstokoe** [exyte/FloatingButton#7]
When using this I get the error `Thread 1: Fatal error: Index out of range`, screenshot below.

![Screenshot 2020-10-02 at 20 36 24](https://user-images.githubusercontent.com/784093/94963638-5df60b00-04f0-11eb-90e7-6c38577f8de0.png)

I've followed the Example code but getting this issue...

```
var body: some View {
    let mainButton2 = AnyView(MainButton(imageName: "ellipsis"))
    
    let textButtons = (0..<MockData.iconAndTextTitles.count).reversed().map { i in
      AnyView(
        IconAndTextButton(
          imageName: MockData.iconAndTextImageNames[i],
          buttonText: MockData.iconAndTextTitles[i]
        )
      )    }
    
    return VStack {
      Spacer().layoutPriority(10)
      
      HStack {
        Spacer().layoutPriority(10)
      
        FloatingButton(mainButtonView: mainButton2, buttons: textButtons)
          .straight()
          .direction(.top)
          .alignment(.right)
          .spacing(10)
          .initialOpacity(0)
      }
    }
  }
```

```
ZStack {
  ....view code
  Button()
}
```

**Comment by benstokoe** [comment]
And when I do get something to work it looks like this (this is the example code now)
![Screenshot 2020-10-02 at 21 23 47](https://user-images.githubusercontent.com/784093/94966696-9d732600-04f5-11eb-8187-a80521faf34f.png)

iOS14 with XCode 12

**Comment by f3dm76** [comment]
@benstokoe Thanks for your report. Fixed the issue. Had to change example's layout a bit cause multiple Spacer().layoutPriority(10) break onPreferencesChanged calls for some reason in the latest swift version, hope Apple fixes this soon. Please check it out in version 0.0.3. Have a marvellous day!
