### ISSUE TITLE
FREE YouTube video tutorial for Floating Button

### ISSUE THREAD

**Issue by rebeloper** [exyte/FloatingButton#9]
Hi, I love Floating Button so much that I have crated a 25 minutes long YouTube video about it. You can take a look at it here:

https://www.youtube.com/watch?v=E3ks0l0Qbkc&list=PL_csAAO9PQ8Zia0zTZZjd0KZBEkcKb4yp&index=2

If you do like it you may want to consider adding it to the README file with this image (people click on images more often than on links):

![FloatingButtons](https://user-images.githubusercontent.com/2488011/105511667-d15a9d00-5cd8-11eb-9190-48ed00884b51.png)

Thanks for the awesome repo again!

**Comment by f3dm76** [comment]
Thank you so much @rebeloper for your kind words, glad you are enjoying it! We will consider it (The name is pronounced just like the word "excite" BTW ;) ) Have a wonderful day, and be sure to check out our other repos!

**Comment by rebeloper** [comment]
Hello again. Do you have any updates on this? Would love to see the video in the README so more people would use Floating Button by learning how to do it with a video. Thanks

**Comment by f3dm76** [comment]
Hello @rebeloper, thank you for your work, but unfortunately we decided not to add this tutorial to readme, have a nice day.
